envs:
  - name: SpatialGym          # registered env name in env_registry.yaml
    n_envs: 50
    data_source: spatial_gym           # nickname for logging
    seed: [0, 49, 1]         # sample n_envs seeds from seed[0] to seed[1], each used at most seed[2] times
    max_turns: 11              # max_exp_steps(10) + cogmap(1); no eval tasks during training
    response_length_per_turn: 2048
    config:
      exp_type: active
      render_mode: vision
      max_exp_steps: 10
      data_dir: vagen/envs/spatial_gym/room_data/1-room
      eval_tasks:
        - task_type: dir
      prompt_config:
        enable_think: true
      require_perception: false
      enable_eval_tasks: false
